### ISSUE TITLE
Exception in Microsoft.Performance.Toolkit.Engine.Engine.Process When Processing Multiple Files

### ISSUE THREAD

**Issue by nibanks** [microsoft/microsoft-performance-toolkit-sdk#139]
**This is from an old-ish build/version of WPA and the plugin framework.**

```
Unhandled exception. Microsoft.Performance.Toolkit.Engine.EngineException: An unexpected error occurred.
 ---> System.ArgumentException: An item with the same key has already been added. Key: QUIC
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Performance.SDK.Runtime.Extensibility.DataExtensions.DataCookers.CrossParserSourceDataCookerRetrieval..ctor(IEnumerable`1 processors)
   at Microsoft.Performance.SDK.Runtime.Extensibility.DataExtensions.DataExtensionFactory.CreateCrossParserSourceDataCookerRetrieval(IEnumerable`1 processors)
   at Microsoft.Performance.Toolkit.Engine.Engine.ProcessCore()
   at Microsoft.Performance.Toolkit.Engine.Engine.Process()
   --- End of inner exception stack trace ---
   at Microsoft.Performance.Toolkit.Engine.Engine.Process()
   at QuicTrace.Program.ProcessTraceFiles(IEnumerable`1 filePaths) in F:\msquic\src\plugins\trace\exe\Program.cs:line 75
   at QuicTrace.Program.Main(String[] args) in F:\msquic\src\plugins\trace\exe\Program.cs:line 679
```

My code:
```c#
var runtime = Engine.Create();
foreach (var filePath in filePaths)
{
    runtime.AddFile(filePath);
}
runtime.EnableCooker(QuicEventCooker.CookerPath);
var results = runtime.Process();  // <=== Throws Exception here!
```
FYI, I tried using `xperf -merge` to merge the two ETLs (client and server) I need to process, but I got the following error:
```
\xperf\xperf -merge rps_client.etl rps_server.etl rps.etl -mergeonly
xperf: error: rps.etl: Indicates two revision levels are incompatible. (0x51a).
```
So, I am blocked right now and need a solution to one of these problems.

**Comment by trgibeau** [comment]
Thanks @nibanks for the report!

Unfortunately ETL files don't have the data capability to support merging or playback across OS reboots and/or different devices. 

The best approach is to process the two ETLs independently and then correlate the data. Let us know if you need any guidance. 

Thanks, 

Tristan
